name: Java CI with Maven & Jacoco

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn -B clean test --file pom.xml
    - name: Jacoco Upload with Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: /home/runner/work/messenger-server/messenger-server/target/site/jacoco/jacoco.xml
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Packaging with Maven
      run: mvn -B package --file pom.xml
    - name: ssh commands execute
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        source: 'views'
        target: ${{ secrets.DEPLOY_SERVER_TARGET }}
